<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.valoury</groupId>
        <artifactId>guilds</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>guilds-server</artifactId>

    <dependencies>
        <dependency>
            <groupId>net.valoury</groupId>
            <artifactId>guilds-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>xyz.refinedev.spigot</groupId>
            <artifactId>Carbon-API</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <minimizeJar>false</minimizeJar>
                            <relocations>
                                <relocation>
                                    <pattern>com.zaxxer.hikari</pattern>
                                    <shadedPattern>net.valoury.guilds.server.lib.hikari</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.postgresql</pattern>
                                    <shadedPattern>net.valoury.guilds.server.lib.postgresql</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.valoury.shared</pattern>
                                    <shadedPattern>net.valoury.guilds.server.lib.shared</shadedPattern>
                                </relocation>
                            </relocations>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
